env:
  global:
    # directory containing the project source
    - REPO_DIR=src/brotli
    # Commit from your-project that you want to build
    - BUILD_COMMIT=v1.0.9
    # pip dependencies to _build_ project
    - BUILD_DEPENDS=
    # pip dependencies to _test_ project
    - TEST_DEPENDS=
    - PLAT=x86_64
    - UNICODE_WIDTH=32
    # PyPI credentials
    - TWINE_USERNAME=anthrotype
    - secure: V39l29da8PcleDHnNv9KsGWeyrnnqiPbo9M7sf6fm1iHWrVyhBiNwtD5AJJiEVvN9ODKyzFgksGvnHuOxmFUcJEqWl4xlY8cynPmNyZbqacPLTI0rb8/At9uWgh14hGd6ZGrSEQtg6e570J3mzl/n5M3MhZkPxGEJ/1j7O5b/iKzSxREB07kH9L0sS7vu0CGAJeAF8MduWZ20vJK5+ahcXbveEqOQLwm/dbB0IkhXofGDqTrLXX0c3ihyeQFtFpH71OVWu5FP4fSg365Mor4DETQoVoTIpAmhIZpE/riEOfJxmNC4bx3j//4zs+Dhx1AhaEs8Wk4i1PGmZBcHELXdwPZpUu6W7mzh3zigYBMjxXIb+K2eD0lBZ8ga22toZ0vQYYMPKqSB2+0hICY0Ait5RpTZegAsqExmgERXW9DkY6OX01h8DCwIvDoaL1c3UblPDcYwAV7Xw9yw0NCJ9O6KlsVjd1E9HSDqbOfD9/llSCUkCZf3tsI2RKDsNCx4CQj9FB3zS3//DLgLYtc69xcNzmSYwy04/sZXPNYjGJfsG/HLJH3jdU1UVcj+KFUAjLbn5j1tdbilv/hdB+MzXjXF6IISNycYXPmEV+36xQ2L7/K1mi9FtRgS1uHZ4n16I/Kxi9bgV4gRDqv2q4HbopoxnGUO/7NCi13XgBzDfU+lAU=

language: generic
dist: xenial
services: docker

matrix:
  include:
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - BUILD_SDIST=true
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - PLAT=i686
    - os: linux
      arch: arm64-graviton2
      dist: focal
      virt: vm
      group: edge
      env:
        - MB_PYTHON_VERSION=3.6
        - PLAT=aarch64
        - DOCKER_IMAGE=quay.io/pypa/manylinux2014_${PLAT}
        - DOCKER_TEST_IMAGE=multibuild/xenial_arm64v8
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
        - PLAT=i686
    - os: linux
      arch: arm64-graviton2
      dist: focal
      virt: vm
      group: edge
      env:
        - MB_PYTHON_VERSION=3.7
        - PLAT=aarch64
        - DOCKER_IMAGE=quay.io/pypa/manylinux2014_${PLAT}
        - DOCKER_TEST_IMAGE=multibuild/xenial_arm64v8
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
        - PLAT=i686
    - os: linux
      arch: arm64-graviton2
      dist: focal
      virt: vm
      group: edge
      env:
        - MB_PYTHON_VERSION=3.8
        - PLAT=aarch64
        - DOCKER_IMAGE=quay.io/pypa/manylinux2014_${PLAT}
        - DOCKER_TEST_IMAGE=multibuild/xenial_arm64v8
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.9
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.9
        - PLAT=i686
    - os: linux
      arch: arm64-graviton2
      dist: focal
      virt: vm
      group: edge
      env:
        - MB_PYTHON_VERSION=3.9
        - PLAT=aarch64
        - DOCKER_IMAGE=quay.io/pypa/manylinux2014_${PLAT}
        - DOCKER_TEST_IMAGE=multibuild/xenial_arm64v8
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.6
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.7
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.8
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.9

before_install:
  - source multibuild/common_utils.sh
  - source multibuild/travis_steps.sh
  - before_install

install:
  - clean_code $REPO_DIR $BUILD_COMMIT
  - build_wheel $REPO_DIR $PLAT

script:
  - install_run $PLAT

after_success:
  # if tagged, create the source distribution and upload to PyPI
  - |
    if [ -n "$TRAVIS_TAG" ] && [ "$TRAVIS_REPO_SLUG" == "google/brotli-wheels" ]; then
      cd ${TRAVIS_BUILD_DIR}
      pip install -U pip
      pip install -U twine
      if [ "$BUILD_SDIST" == true ]; then
        pip install -U setuptools
        (cd $REPO_DIR && python setup.py sdist --formats=zip)
        twine upload $REPO_DIR/dist/*.zip
      fi
      twine upload wheelhouse/*.whl
    fi
